### ISSUE TITLE
AMP Support

### ISSUE THREAD

**Issue by vpsop** [KevinBatdorf/code-block-pro#108] opened 2023-01-13 11:10 UTC
Hi, It will be great if this plugin supports AMP.

The official AMP plugin warns that this plugin is not AMP compatible.

![Image](https://user-images.githubusercontent.com/57450981/212306526-66a469df-0c15-4f86-bee2-1fa864dd7d1e.png)

**Comment by KevinBatdorf** [comment] 2023-01-13 15:04
Thanks for reporting this. I'll look into this and follow up in a few hours.

**Comment by KevinBatdorf** [comment] 2023-01-13 16:43
I couldn't reproduce it. Can you expand the info there and share the data. Just make sure there's nothing personal in there you don't want public. 

I did get a warning about WooCommerce, for example:

![Screen Shot 2023-01-13 at 11 41 49 AM](https://user-images.githubusercontent.com/1478421/212373142-7ec30cd8-64a2-463b-92a9-c8efe79f506e.png)

**Comment by KevinBatdorf** [comment] 2023-01-28 16:48
Closing this but if you want to still work on this let me know

**Closed by KevinBatdorf** 2023-01-28 16:48 UTC
