### ISSUE TITLE
The unfiltered_html capability is required to edit this block. Contact an admin to enable this feature. 

### ISSUE THREAD

**Issue by Varsha176** [KevinBatdorf/code-block-pro#235] opened 2023-08-15 10:49 UTC
Wordpress Admin is not able to edit the code. On editing the post getting "The unfiltered_html capability is required to edit this block. Contact an admin to enable this feature. This is not an error." issue. 
 This user is the admin.

<img width="855" alt="Screenshot 2023-08-15 at 4 18 07 PM" src="https://github.com/KevinBatdorf/code-block-pro/assets/18423768/dd0ca6e8-f1de-42f6-9d6e-eef14106b7c4">

**Comment by KevinBatdorf** [comment] 2023-08-15 11:48
Is there a reason that capability is disabled for that user?

The plugin stores an SVG in the database which WP requires that capability for. I don't have a good way around it at the moment so it's required at least for now.

**Comment by Varsha176** [comment] 2023-08-16 09:49
User is 'Admin'. I have not make any changes for the user's capability.

**Comment by KevinBatdorf** [comment] 2023-08-16 13:15
Can you debug a bit by deactivating other plugins (start with all and check)? If we can identify the conflicting code I should be able to fix it.

**Comment by vishnumaiea** [comment] 2023-10-02 19:40
I am also facing the same issue. WordPress version is 6.3.1. Asking users to disable the plugins of a running website in order to debug an issue is not always a good idea. I have seen many developers asking that same thing. But I think it is an inherent problem of WordPress that we have to live with for now.

Coming back to the issue, I was able to find the source of the problem, at least for me, as the [All In One SEO](https://wordpress.org/plugins/all-in-one-seo-pack/) plugin. I disabled each plugin one at a time until I got the issue resolved. I created a separate staging area for my site, thanks to Hostinger, without affecting my main website.

**Comment by KevinBatdorf** [comment] 2023-10-02 19:48
> Asking users to disable the plugins of a running website in order to debug an issue is not always a good idea. I have seen many developers asking that same thing. But I think it is an inherent problem of WordPress that we have to live with for now.

You can use the health check plugin too if youre not able to disable plugins: https://wordpress.org/plugins/health-check/

> Coming back to the issue, I was able to find the source of the problem, at least for me, as the [All In One SEO](https://wordpress.org/plugins/all-in-one-seo-pack/) plugin

Interesting. i'll try to install it and see if I can reproduce it to see why it's happening.

**Comment by vishnumaiea** [comment] 2023-10-02 19:57
Thanks for the tip on the Health Check plugin. Looks like WP team has addressed it the way it should be.

**Comment by KevinBatdorf** [comment] 2023-10-02 19:59
I agree it should be in core though. Maybe someday they will merge it in.

**Comment by KevinBatdorf** [comment] 2023-10-07 17:39
Unfortunately I can't reproduce this. It could be that there's a conflict between AIOSEO, Code Block Pro and another plugin, and it requires all three to be active. Or it could be a setting I need to toggle in AIOSEO specifically. Or it could be something totally random.

Any ideas? If you want to list your plugins I can try installing all of them to debug more thoroughly. 

![CleanShot 2023-10-07 at 13 37 25](https://github.com/KevinBatdorf/code-block-pro/assets/1478421/55776051-6946-4bc1-bc3d-840eb9f0da8d)

**Comment by KevinBatdorf** [comment] 2023-10-12 00:19
Latest version has a fix for this that I hope works. It grabs the value from the browser (that gets it from the server via REST) instead of sending it with the html document directly. 

If it's not working, let me know. I couldn't reproduce it so I'm not 100% confident it resolved it

**Closed by KevinBatdorf** 2023-10-12 00:19 UTC

**Comment by vishnumaiea** [comment] 2023-10-12 09:42
I have uninstalled the AIOSEO plugin and am currently using a different one. I have been thinking of switching to a different SEO plugin anyway. I still have the staging area active. So I will test if the fix works there.

**Comment by KevinBatdorf** [comment] 2023-10-12 14:40
Curious what you switched to

**Comment by vishnumaiea** [comment] 2023-10-12 16:00
Using RankMath SEO plugin now. Better and faster than AIOSEO 😁
